### ISSUE TITLE
pass variable from doc to index.js

### ISSUE THREAD

**Issue by chrisopedia** [SassDoc/sassdoc-theme-default#100]
I've noticed that I can pass a variable in the `gulp-sassdoc` to the views in my theme using the `views.{variable}`, but how do I pass this variable to the `ctx` or `index.js` so I can parse it and modify it for my views?

**Comment by pascalduez** [comment]
Hi @chrisopedia,

I'm not sure to fully understand, could you give us a bit more details/context?
Passing additional stuff to `sassdoc-theme-default` won't have much effect, since the theme will not make any use of it. 

If your building a custom theme, that's another story.
You can gain quite some advanced control in your theme `index.js`.
Also have a look at `sassdoc-extras` where we do data transformations and additions.

**Comment by chrisopedia** [comment]
I figure it out. Thanks.
